set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'ambv/black'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'shime/vim-livedown'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sensible'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-syntastic/syntastic'
Plugin 'vimwiki/vimwiki'
Plugin 'wakatime/vim-wakatime'
Plugin 'altercation/vim-colors-solarized'
call vundle#end()
filetype plugin indent on
colorscheme solarized
set backspace=eol,start,indent
set background=light
set encoding=utf8
set ffs=unix,dos,mac
set hlsearch
set incsearch
set lazyredraw
set laststatus=2
set magic
set mat=2
set mouse=r
set nobackup
set noerrorbells
set noswapfile
set novisualbell
set nowritebackup
set number
set ruler
set showmatch
set noshowmode
set smartindent
set splitbelow
set splitright
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatusLineFlag()}
set statusline+=%*
set ttimeoutlen=50
set whichwrap+=<,>,h,l
set wildignore+=*/bazel-bin/*
set wildignore+=*/bazel-genfiles/*
set wildignore+=*/bazel-out/*
set wildignore+=*/bazel-testlogs/*
set wildignore+=*/bin/*
set wildignore+=*/include/*
set wildignore+=*/lib/*,*/lib64/*
set wildignore+=*/media/*
set wildignore+=*/man/*
set wildignore+=*/share/*
set wildignore+=*.pyo,*.pyc,*/__pycache__/*
set wildignore+=*.sqlite3
set wildmenu
set wildmode=longest:full
set wrap
syntax enable
vnoremap <silent> * :call VisualSelection('f')<CR>
vnoremap <silent> # :call VisualSelection('b')<CR>
let g:airline_powerline_fonts=1
let g:airline_theme='base16'
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = "unique_tail_improved"
let g:ctrlp_follow_symlinks = 1
let g:go_def_mapping_enabled = 0
let g:jedi#completions_enabled=1
let g:jedi#popup_on_dot=0
let g:jedi#show_call_signatures=2
let g:NERDTreeIgnore=['__pycache__']
let g:solarized_bold=0
let g:solarized_italic=0
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open=1
let g:syntastic_check_on_wq=0
let g:syntastic_c_checkers = ['splint', 'clang_check', 'make', 'gcc']
let g:syntastic_html_checkers = ['tidy']
let g:syntastic_javascript_checkers=['eslint']
let g:syntastic_python_checkers = ['flake8']
augroup black
    autocmd BufWritePre *.py execute ':Black'
augroup END
nmap <leader>ne :NERDTreeToggle<cr>
